### ISSUE TITLE
Moderators Implement

### ISSUE THREAD

**Issue by Gnagnom94** [kamikazechaser/GroupThorBot#1]
I need people who aren't administrators but can use only the basic commands, like a moderator of the group.

**Comment by kamikazechaser** [comment]
That feature was there in the older version. I will look into it to see if I can port it.

**Comment by kamikazechaser** [comment]
https://github.com/groupforspeed/anti-spam-API/blob/b5f14622a6fd316f71acc73c5fc9bd9a71f8dfd8/plugins/mod.lua

**Comment by kamikazechaser** [comment]
unfortunately porting this would break the bot. However, I will soon introduce [ThorsHammer](https://github.com/kamikazechaser/ThorsHammer) which I have written in JS it has that function, Keep an eye on that project!
